### ISSUE TITLE
Retry-mekanisme for systembruker

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-backend#236]
2021-04-19 11:41:50.388 CESTCaused by: java.lang.NullPointerException
Default
2021-04-19 11:41:50.388 CEST at no.roedt.ringesentralen.token.TokenService.loginSomSystembruker(TokenService.kt:49)
Default
2021-04-19 11:41:50.388 CEST at no.roedt.ringesentralen.token.TokenService.login(TokenService.kt:35)
Default
2021-04-19 11:41:50.388 CEST at no.roedt.ringesentralen.token.TokenService_ClientProxy.login(TokenService_ClientProxy.zig:163)
Default
2021-04-19 11:41:50.388 CEST at no.roedt.ringesentralen.token.TokenController.login(TokenController.kt:33)
Default
2021-04-19 11:41:50.388 CEST at no.roedt.ringesentralen.token.TokenController_Subclass.login$$superaccessor1(TokenController_Subclass.zig:269)
Default
2021-04-19 11:41:50.388 CEST at no.roedt.ringesentralen.token.TokenController_Subclass$$function$$1.apply(TokenController_Subclass$$function$$1.zig:33)
Default
2021-04-19 11:41:50.388 CEST at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
Default
2021-04-19 11:41:50.388 CEST at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:24)
Default
2021-04-19 11:41:50.388 CEST at io.quarkus.security.runtime.interceptor.PermitAllInterceptor.intercept(PermitAllInterceptor.java:23)
Default
2021-04-19 11:41:50.388 CEST at io.quarkus.security.runtime.interceptor.PermitAllInterceptor_Bean.intercept(PermitAllInterceptor_Bean.zig:327)
Default
2021-04-19 11:41:50.388 CEST at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
Default
2021-04-19 11:41:50.388 CEST at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
Default
2021-04-19 11:41:50.388 CEST at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:127)

**Comment by madsop** [comment]
Viste seg at det var systembrukaren som mangla i prod.
