### ISSUE TITLE
NPE i postSvarFraTelefonsvarer

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-backend#244]
2021-04-27 10:23:25.621 CESTCaused by: java.lang.NullPointerException
Default
2021-04-27 10:23:25.621 CEST at no.roedt.ringesentralen.samtale.telefonsvarer.TelefonsvarerService.postSvarFraTelefonsvarer(TelefonsvarerService.kt:31)
Default
2021-04-27 10:23:25.621 CEST at no.roedt.ringesentralen.samtale.telefonsvarer.TelefonsvarerController.postSvarFraTelefonsvarer(TelefonsvarerController.kt:37)
Default
2021-04-27 10:23:25.621 CEST at no.roedt.ringesentralen.samtale.telefonsvarer.TelefonsvarerController_Subclass.postSvarFraTelefonsvarer$$superaccessor1(TelefonsvarerController_Subclass.zig:358)
Default
2021-04-27 10:23:25.621 CEST at no.roedt.ringesentralen.samtale.telefonsvarer.TelefonsvarerController_Subclass$$function$$1.apply(TelefonsvarerController_Subclass$$function$$1.zig:41)

**Comment by madsop** [comment]
Systembrukaren i databasen var ufullstendig.
