### ISSUE TITLE
Får outofbounds ved manglande telefonnummer i HyperSys

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-backend#42]
2021-02-04 16:04:49.303 CETCaused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
Default
2021-02-04 16:04:49.303 CET at java.util.Collections$SingletonList.get(Collections.java:4849)
Default
2021-02-04 16:04:49.303 CET at no.roedt.ringesentralen.hypersys.ModelConverter.toTelefonnummer(ModelConverter.kt:34)

**Comment by madsop** [comment]
Trur dette problemet no er løyst.
