### ISSUE TITLE
Exception i bakgrunnen frå io.grpc

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-backend#46]
2021-02-04 19:14:51.660 CET2021-02-04 18:14:51,659 SEVERE [io.grp.int.ManagedChannelOrphanWrapper] (executor-thread-1) *~*~*~ Channel ManagedChannelImpl{logId=1, target=secretmanager.googleapis.com:443} was not shutdown properly!!! ~*~*~*
Default
2021-02-04 19:14:51.660 CET Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.: java.lang.RuntimeException: ManagedChannel allocation site
Default
2021-02-04 19:14:51.660 CET at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
Default
2021-02-04 19:14:51.660 CET at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:612)
Default
2021-02-04 19:14:51.660 CET at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1600(InstantiatingG

**Comment by madsop** [comment]
Ser ut som problemet her er at vi kallar SecretManagerServiceClient.create() ved kvart kall til GCP. Kan heller initialisere denne ved oppstart.
